name: "demo-jfrog-gitbub-oidc-docker-publish"
on: push

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write
jobs:
  build:
     runs-on: ubuntu-latest
     env:
      #OIDC_AUDIENCE: 'jfrog-github'
      OIDC_PROVIDER: 'deepu19t'
      PLATFORM_REPO: 'blr-td-virtual'
      JF_URL: 'https://psemea.jfrog.io'
     steps:
       - name: Checkout
         uses: actions/checkout@v3
              
       - name: Setup Node docker
         uses: actions/setup-node@v3

       - name: Get id token
         run: |
          ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=access-oidc-demo" | jq .value | tr -d '"')
          echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV
       
       - name: Exchange token with access
         env:
          ID_TOKEN: ${{ env.ID_TOKEN }}
          ARTIFACTORY_URL: ${{ secrets.JF_URL }}
         run: |
          ACCESS_TOKEN=$(curl -XPOST -H "Content-Type: application/json" \
          "${ARTIFACTORY_URL}/access/api/v1/oidc/token" \
          -d "{\"provider_name\":\"deepu19t\", \
          \"subject_token\": \"${ID_TOKEN}\", \
          \"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \
          \"subject_token_type\": \"urn:ietf:params:oauth:token-type:id_token\"}" \
          | jq .access_token | tr -d '"')
          echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV  
  
       - name: Setup jfrog cli
         uses: jfrog/setup-jfrog-cli@v3
         env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
          
       - name: Perform Docker Login
         env:
          JF_ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
         run: |
           echo '${{ env.JF_ACCESS_TOKEN }}'
           echo '${{ env.ACCESS_TOKEN }}'
           jf docker login '${{ env.JF_URL }}/' --username 'deepakt@jfrog.com' --password '${{ env.ACCESS_TOKEN }}'

       - name: Perform Docker Build Image
         run: jf docker build -t 'psemea.jfrog.io/${{ env.PLATFORM_REPO }}/docker-oidc-publish:${{ github.run_number }}' .
           
       - name: Perform Docker Push Image
         run: jf docker push 'psemea.jfrog.io/${{ env.PLATFORM_REPO }}/docker-oidc-publish:${{ github.run_number }}' --build-name=github-docker-oidc-publish --build-number=${{ github.run_number }}
         
       - name: Perform Docker Publish Build Info With JFrog CLI
         run: |
          # Collect environment variables for the build
          jf rt bce github-docker-oidc-publish ${{ github.run_number }}
          # Collect VCS details from git and add them to the build
          jf rt bag github-docker-oidc-publish ${{ github.run_number }}
          # Publish build info
          jf rt bp github-docker-oidc-publish ${{ github.run_number }}   
   
      # - name: Setup JFrog CLI
      #   uses: jfrog/setup-jfrog-cli@v3
      #   env:  
     #      JF_URL: 'https://psemea.jfrog.io'
     #    with:
      #     oidc-provider-name: ${{ env.OIDC_PROVIDER }}
      #     #oidc-audience: ${{ env.OIDC_AUDIENCE }}
       #- name: Set CLI Config
       #  run: jf docker build -t psemea.jfrog.io/${{ env.PLATFORM_REPO }}/docker-oidc-publish:${{ github.run_number }} .
           
      # - name: Push Image
      #   run: jf docker push psemea.jfrog.io/${{ env.PLATFORM_REPO }}/docker-oidc-publish:${{ github.run_number }} --build-name=docker-oidc-publish --build-number=${{ github.run_number }}
         
      # - name: Publish Build info With JFrog CLI
      #   run: |
          # Collect environment variables for the build
      #    jf rt bce docker-oidc-publish ${{ github.run_number }}
          # Collect VCS details from git and add them to the build
      #    jf rt bag docker-oidc-publish ${{ github.run_number }}
          # Publish build info
      #    jf rt bp docker-oidc-publish ${{ github.run_number }}         
          
