name: "Demo-jfrog-gitbub-oidc-docker-publish"
on: push

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write

jobs:
  build:
     runs-on: ubuntu-latest
     env:
      #OIDC_AUDIENCE: 'jfrog-github'
      OIDC_PROVIDER: 'deepu19t'
      PLATFORM_REPO: 'docker-virtual-repo'
     steps:
       - name: Checkout
         uses: actions/checkout@v3
              
       - name: Setup Node docker
         uses: actions/setup-node@v3
   
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v3
         env:  
           JF_URL: ${{ secrets.JF_URL }}
         with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           #oidc-audience: ${{ env.OIDC_AUDIENCE }}

       - name: Set CLI Config
         run: jf docker --build-name=docker-virtual-repo --build-number=1
           
       - name: Install Dependencies
         run: jf rt dp psemea.jfrog.io/artifactory/api/docker/blr-docker-ps-td:latest docker --build-name=docker-build --build-number=1.0.0
         
       - name: Publish
         run: docker push psemea.jfrog.io/blr-docker-ps-td/ubuntu:latest
         
       - name: Publish Build info With JFrog CLI
         run: |
          # Collect environment variables for the build
          jf rt bce jfrog-gitbub-oidc-npm-publish ${{ github.run_number }}
          # Collect VCS details from git and add them to the build
          jf rt build-add-git jfrog-gitbub-oidc-npm-publish ${{ github.run_number }}
          # Publish build info
          jf rt bp jfrog-gitbub-oidc-npm-publish ${{ github.run_number }}
